"""Add drive_file_id to upload_music

Revision ID: 605fa91c7af5
Revises: 88ace9d8e792
Create Date: 2024-09-29 01:35:53.873667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605fa91c7af5'
down_revision = '88ace9d8e792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_file_id', sa.String(length=256), nullable=False))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        batch_op.drop_column('drive_file_id')

    # ### end Alembic commands ###
