"""UploadMusic Added

Revision ID: 88ace9d8e792
Revises: c6c2f1565218
Create Date: 2024-03-28 19:30:30.664059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ace9d8e792'
down_revision = 'c6c2f1565218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('uploader_username', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_music')
    # ### end Alembic commands ###
